services:
  hermess:
    build: .
    container_name: hermess
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - hermess_logs:/var/log/hermess
      - ./.env:/config/.env

volumes:
  hermess_logs:
