CUSTOM_NAME="example-miner"
CUSTOM_VERSION="1.0.0"
CUSTOM_LOG_BASENAME="/var/log/miner/example-miner/example-miner"
CUSTOM_TEMPLATE="%WAL%.%WORKER_NAME%"
CUSTOM_URL="pool.example.com:3333"
CUSTOM_ALGO="examplealgo"
CUSTOM_USER_CONFIG=""
CUSTOM_BUILD_TARGETS="GPU_NVIDIA"
CUSTOM_DESCRIPTION="Example HiveOS custom miner package"

